path: '/content/gdrive/MyDrive/Colab Notebooks/image-segmentation-yolov8/data/'
train: '/content/gdrive/MyDrive/Colab Notebooks/image-segmentation-yolov8/data/images/train' 
val: '/content/gdrive/MyDrive/Colab Notebooks/image-segmentation-yolov8/data/images/val' 

nc: 8
names: ['good_luck', 'hello', 'ily', 'no', 'please', 'sorry', 'thank_you', 'yes']
