path: C:/Users/ESPB/Music/image-segmentation-yolov8/data
train: C:/Users/ESPB/Music/image-segmentation-yolov8/data/images/train 
val: C:/Users/ESPB/Music/image-segmentation-yolov8/data/images/val  

nc: 8
names: ['good_luck', 'hello', 'ily', 'no', 'please', 'sorry', 'thank_you', 'yes']
